---
# defaults file for create_multinode
multinode_file_path: "kolla-inventory"
vm_list_path: "vm_list.yml"
ansible_args: >-
  ansible_ssh_user={{ kolla_user }}
  ansible_become=True
  ansible_private_key_file={{ kolla_ssh_key }}
  ansible_python_interpreter={{ kolla_python_interpereter }}
# Deafult number of CPU allocated to each node
# it's recommended to allocate max CPUs
default_cpu: 12
# Default RAM for each node
# Minimal 1GB RAM to boot the image
default_ram: 1024
# Default RAM for each node
# Minimal 25GB to boot the image
default_disksize: 25
is_remote: false
use_node_names: true
nodes: []
