# defaults file for multinode Openstack

# Directory where the disk images will be located
# default is the libvirt image pool
# make sure you have enough disk space on the partition
# if not then change to something on your /home
image_pool: "/var/cache/libvirt"
# Path to the base node image
image_path: "{{image_pool}}/kolla-image.qcow2"
# Network interfaces

# 192.168.122.0/24
# could also be the "default" network that libvirt created

network_ssh: "nat1"
# 192.168.123.0/24
network_openstack: "nat2"
# 192.168.100.0/24
network_neutron: "nat3"

# Whether this setup is for all-in-one deployment
# keep `false` for multinode
is_aio: false


# Absolute path to the ssh key
# TODO: figure out how to do this without using absolute path
# Either copy key from ssh/id_kolla to your .ssh directory
# or modify this config to point to ssh/id_kolla
kolla_ssh_key: "{{ lookup('ansible.builtin.env','HOME')}}/.ssh/id_kolla"

# Add nodes to your ssh config
# this way you can easily ssh into nodes by
# ssh <node-name>
# Warning, this edits your ssh config
# off by default
edit_ssh_config: false
# your ssh config location
ssh_config: "{{ lookup('ansible.builtin.env','HOME')}}/.ssh/config"

# globals file (located in kolla-files) subdirectory
# this is usefull if you have several deployment scenarios
# i.e. you develop on multiple branches at once
globals_file: globals.yml

# Path to kolla-ansible source code
kolla_source_host_path: "./kolla-ansible"

# # Default node resources

# Deafult number of CPU allocated to each node
# it's recommended to allocate max CPUs
default_cpu: 12
# Default RAM for each node
# Minimal 1GB RAM to boot the image
default_ram: 1024
# Default RAM for each node
# Minimal 25GB to boot the image
default_disksize: 25

# # Node configuration
# each node can be of different typr
#   control: for openstack control plane components
#   network: for openstack networking services
#   compute: openstack compute host
#   storage: for storage services
#   monitoring: for monitoring services
#   deployment: for running kolla-ansible itself, not part of openstack
# You need exactly one deployment and at least one workload (everything else) node
# You have to have the deploy node separated from everything else
# unless you deploy in aio mode, in which case use different config
# file (TODO)
# You can edit ram_size disk_size and cpu_count for each node

# 4+1 node example (3 compute nodes, one control node, one deployment node)
# You can add more if you wish, or create dedicated network nodes for example
nodes:

# # Controll node
# Hosts everything that is not compute

  - name: "openstack-control"
    control: true
    storage: true
    monitoring: true
    network: true
# false is the default option for each node type
    compute: false
#  minimum ram for this node
    ram_size: 8192
    disk_size: 25
#   cpu_count: 12

# # Compute  nodes
# For compute instances
  - name: "openstack-compute-01"
    compute: true
    ram_size: 4096

  - name: "openstack-compute-02"
    compute: true
    ram_size: 4096

  - name: "openstack-compute-03"
    compute: true
    ram_size: 4096
# # Deployment node
# SSH into this node and run kolla
  - name: "openstack-deployment"
    deployment: true
    ram_size: 1024


