---
- name: Prepare Kolla Nodes
  hosts: all
  user: root
  gather_facts: yes
  vars:
    ansible_ssh_common_args: '-o IdentitiesOnly=yes'
  roles:
    - prepare_nodes

- name: Upload files to deploy node
  hosts: deployment
  user: root
  vars:
    ansible_ssh_common_args: '-o IdentitiesOnly=yes'
  roles:
  - name: "upload_to_nodes"
    vars:
      source_host_path: "{{ kolla_source_host_path }}"
  - name: git_patch
    when: git_patch_kolla
    delegate_to: localhost
  - name: "upload_to_nodes"
    vars:
      source_host_path: "{{  patched_git_repo if git_patch_kolla  else kolla_source_host_path }}"
      source_node_path: "{{ kolla_source_node_path }}"
