---
# tasks file for get_ip
- block:
  - name: Gather information about network managed by 'libvirt' remotely using uri
    virt_net:
      command: info
    register: networks
  # - debug:
  #     msg: "mac: {{mac}}, interface: {{interface}}, machine_name: {{machine_name}}"
  - debug:
      msg: "{{ networks.networks[interface].dhcp_leases }}"
  - name: "Get IP adress of a node"
    set_fact:
      current_ip: "{{ networks.networks[interface].dhcp_leases | selectattr('mac','equalto',mac) | map (attribute='ipaddr')| join(',') }}"
  when: current_ip is not defined or not current_ip

- name: Wait {{getip_delay}} seconds before retrying task
  pause:
    seconds: "{{ getip_delay }}"
  when: current_ip is not defined or not current_ip
