- name: Reset Current IP
  set_fact:
    current_ip: ''

- name: Loop get IP
  include_tasks: getip.yml
  with_sequence: start=1 end={{ getip_retries }}

- name: "Fallback to default IP if no IP found"
  set_fact:
    current_ip: "{{ machine_name | upper }}_IP_NOT_FOUND"
  when: not current_ip

- debug:
    msg: "{{current_ip}}"
