---
- name: Auto-generate new MAC addresses for the interfaces
  set_fact:
    network_ssh_mac: "{{ '52:54:00' | random_mac }}"
    network_openstack_mac: "{{ '52:54:00' | random_mac }}"
    network_neutron_mac: "{{ '52:54:00' | random_mac }}"

- name: Auto-generate new IP addresses for the interfaces
  set_fact:
    gen_ip_ssh: >-
      {{ ((gen_ip_ssh ~ '/24') | ipaddr('next_usable'))  if gen_ip_ssh is defined
      else network_ssh_ip_range | ipaddr('next_usable') }}

- name: Reserve IP addresses for SSH network
  community.libvirt.virt_net:
    name: "{{ network_ssh }}"
    command: "modify"
    xml: "<host mac='{{ network_ssh_mac }}' name='{{ node_name }}' ip='{{ gen_ip_ssh }}'/>"
